### ISSUE TITLE
Crashed When Look To Laser Relay

### ISSUE THREAD

**Issue by kenijey** [cubex2/BetterFonts#11]
from the actually additions mod. and also using theoneprobe. using game 1.11.2, forge 2228, latest better fonts
[crash-2017-02-12_14.10.55-client.txt](https://github.com/cubex2/BetterFonts/files/769230/crash-2017-02-12_14.10.55-client.txt)
 here is the crash report.

**Comment by SDUBZ** [comment]
also got this problem 
[crash-2017-02-26_12.38.28-client.txt](https://github.com/cubex2/BetterFonts/files/801681/crash-2017-02-26_12.38.28-client.txt)

**Comment by kenijey** [comment]
i hope new update didn't fix only actually additions compatibility problem, hope it contains custom font using mods compatibility.
