### ISSUE TITLE
Rendering issue with Refined Storage Grid

### ISSUE THREAD

**Issue by misterfixit** [cubex2/BetterFonts#3]
http://puu.sh/pyKbM.png

the picture above shows that the text is having overlay issues most notably the flint is overlapping the item count in the grid, is there any way to fix this. I have posted a similar issue on the Refined Storage github as well.
Fyi this happens accross multiple font types, I have not found one that doesn't have this issue.

**Comment by misterfixit** [comment]
https://github.com/raoulvdberge/refinedstorage/issues/129

**Comment by raoulvdberge** [comment]
For the author of BetterFonts, this is the part of the code where I'm rendering that text:

https://github.com/raoulvdberge/refinedstorage/blob/mc1.9.4/src/main/java/refinedstorage/gui/GuiBase.java#L210-L230

**Comment by cubex2** [comment]
The problem seems to be that the font is scaled down to a point where some parts disappear. To minimize that effect you can either increase your gui scale or if your resolution doesn't allow that, use a bold font. SansSerif also seems to look good.

**Comment by misterfixit** [comment]
That puush link is using SansSerif

**Comment by cubex2** [comment]
One way to avoid the scaling problem is to use a smaller font size when drawing small text. That however would require mods to explicitly do that in their code.
