### ISSUE TITLE
Why doesn't it work?

### ISSUE THREAD

**Issue by Pr0K0ck4** [cubex2/BetterFonts#4]
When I installed it, it didn't do anything. I tried to re-install its config, but it didn't work eather. What could possibly cause this?
![mod page](https://cloud.githubusercontent.com/assets/20193197/16428420/197b4a16-3d72-11e6-8ea7-f411ae03589a.PNG)
![main page](https://cloud.githubusercontent.com/assets/20193197/16428419/1978d6fa-3d72-11e6-9e21-0e1a7e0a43fa.PNG)

**Comment by cubex2** [comment]
I forget to update some mappings causing it to only work in my dev environment. It should now work.
